### ISSUE TITLE
AttributeError: module 'ClusterPoints' has no attribute 'classFactory' 

### ISSUE THREAD

**Issue by MargaritaGarfias** [jjenkner/ClusterPoints#2]
Hi 

I am trying to run the plugin in QGIS bit it won't let me load it 'due to an error when calling its classFactory() method'. 

I have used the plugin before with this version of QGIS with no issues. Only noticed the issue when trying to replicate my exercise yesterday. The error appeared when trying to load the plugin before and after updating it. The following error log appears: 

AttributeError: module 'ClusterPoints' has no attribute 'classFactory' 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
AttributeError: module 'ClusterPoints' has no attribute 'classFactory'

Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] 
QGIS version: 3.4.3-Madeira Madeira, exported

**Comment by jjenkner** [comment]
Hmm,

I reinstalled Python 3.6.0 and QGIS 3.4.3-Madeira Madeira on my MacBook Air. Then I downloaded ClusterPoints plugin from the official repository and the clustering does work with my test data. 

I do not know who the culprit is within your installation at the moment ...

Could you try reinstalling the ClusterPoints plugin?

**Comment by MargaritaGarfias** [comment]
Hi

I have uninstalled the plugin and the same error appears when I try reinstalling it ("`Couldn't load plugin 'ClusterPoints' due to an error when calling its classFactory() method`") . And then the plugin appears back in my installed plugins when I close the error dialogue box. 
The same error appears when I untick and tick the plugin again... I don't don't what is happening. I tried downloading the zip version from github but it seems that the version is not compatible with my QGIS version. And the new QGIS version is not compatible with my macOS version (Sierra 10.12.6).

**Comment by jjenkner** [comment]
Hi,

the error should be fixed now. Check out the new version 3.3.1 in the QGIS plugin repository.

:-)

**Comment by jjenkner** [comment]
Hi

I made an effort and changed the whole plugin structure in all versions. 3.3 should be working for you now :-)

Johannes

**Comment by jjenkner** [comment]
The new version is online now. However, I had to change theme of the parent folder of the plugin. Hence, you need to deinstall the plugin, then restart QGIS and install the plugin again. From then on, it should work without any problems :-)

**Comment by MargaritaGarfias** [comment]
Hi Johannes

Uninstalled and restarted everything. Gave it a try and seems like it's all working now! Thanks a lot for the fix!
