### ISSUE TITLE
Please fix bugtracker link

### ISSUE THREAD

**Issue by pcav** [jjenkner/ClusterPoints#2]
It currently points to the repo page instead of the issue one.

**Comment by jjenkner** [comment]
Hi Paolo,

OK I will make an effort to finish this plugin development. However, I already lost my credentials on the OSGEO plugin development. Where do I have to log on again to make changes?

Sorry for the mess, but I was too busy with other work ...

**Comment by pcav** [comment]
Sure, no worries!
Thanks a lot.

**Comment by jjenkner** [comment]
Sorry, but I need to know where to change the link for issues. Can you tell me the url?

**Comment by pcav** [comment]
https://github.com/jjenkner/ClusterPoints/issues/

**Comment by pcav** [comment]
Fixed, thanks.
