### ISSUE TITLE
Please remove unnnecessary files

### ISSUE THREAD

**Issue by pcav** [jjenkner/ClusterPoints#3]
.pyc etc.
They are generated automatically during installation.
Furthermore, there is probably some leftover (ftools) from older versions.
Thanks.

**Comment by jjenkner** [comment]
.pyc is removed now. ftools is needed in the original version of the plugin.

**Comment by jjenkner** [comment]
I wiped out the old repository and created it new, since I needed to change the package name of the plugin. It was only possible like that. The files in there are roughly the same as before ...
