### ISSUE TITLE
Better organization of code

### ISSUE THREAD

**Issue by pcav** [jjenkner/ClusterPoints#4]
Please avoid putting different versions in different folders. You can manage this with releases and branches.

**Comment by jjenkner** [comment]
OK I will do so :-)

**Comment by jjenkner** [comment]
Done using branches.

**Comment by pcav** [comment]
I'd suggest moving all to the top directory.
See most other plugins as an examples.

**Comment by jjenkner** [comment]
Done.

**Comment by jjenkner** [comment]
Thank you :-)
