### ISSUE TITLE
Script won't finish

### ISSUE THREAD

**Issue by dingausmwald** [jjenkner/ClusterPoints#5]
The script won't finish with qgis 3.16.11.

Logs say
...
2021-10-25T23:52:19     INFO    95% of cluster tree built
2021-10-25T23:52:19     INFO    Cluster tree fully computed

but status bar won't end. Esp. in modeler this freezes qgis.
Attributes are created (at least for SLINK), but layer stays in edit mode.

**Comment by jjenkner** [comment]
This is a bug in the latest QGIS versions. I just uploaded a new version (4.12) of the plugin with a work-around to fix this issue. Feel free to download the new version after approval by an administrator.

**Comment by dingausmwald** [comment]
Just tested it and it works. Three additions: 
1. You marked the new version with minimum qgis verion 3.18, but it works with 3.16, which still is ltr. So i couldnt update it from the plugins menue and had to do it manualy. Maybe you could change this.
2. The plugin changes the layer instead of creating a new one. This is different to other plugins, which could lead to problems/confusion when used in the modeler.
3. The clustersize has to be defined. Could you change it so the clustersize can be 0 or something so it calculates the clustersize on its own? This would be awesome. There is just a plugin in 2.18 which i know is capable of defining the cluster size on its own (scipy cluster).
I know the last two are more of a feature inquiry than an addition to the discussed bug.

**Comment by jjenkner** [comment]
Thank you for testing the plugin and for your hints!

1. I now also assigned qgis version 3.16 to the plugin.

2. I will keep this in mind for future versions

3. Thank you for the idea. However, I cannot think of a reasonable algorithm which provides the cluster size on its own. If I find one, I will consider this.
